# Generated by Django 6.0 on 2025-12-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('hh_employer_id', models.CharField(max_length=50, unique=True, verbose_name='ID на HH.ru')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(default='', max_length=50, unique=True, verbose_name='ID вакансии на HH')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='RUR', max_length=10, verbose_name='Валюта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('experience', models.CharField(default='Не указано', max_length=50, verbose_name='Опыт работы')),
                ('employment_mode', models.CharField(default='Полный день', max_length=50, verbose_name='Формат работы')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.employer', verbose_name='Компания')),
                ('skills', models.ManyToManyField(related_name='vacancies', to='vacancies.skill', verbose_name='Ключевые навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
